config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :books
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      end
    end

    def guest_user?
      email == GUEST_USER_EMAIL
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      flash.now[:alert] = "An error has occurred.Please try again later"
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new()
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      @user = current_user
      flash.now[:notice] = "An error has occurred.Please try again later."
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    user = User.find(@book.user_id)
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "An error has occurred.Please try again later"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @user = current_user

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params_update)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      flash.now[:notice] = "An error has occurred.Please try again later."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end

  def user_params_update
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h1>User info</h1>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-sm btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>

      <h1>New book</h1>
      <%= form_with model: Book.new do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %><br>
        <%= f.submit 'Create Books', class: "btn btn-success" %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		
  		<% if @book.errors.any? %>
        <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book do |f| %>

        <h4>Title</h4>
        <%= f.text_field :title %>
  
        <h4>Opinion</h4>
        <%= f.text_area :body %><br>
  
        <%= f.submit 'Update Book', class: "btn btn-success" %><br>
  
        <span>
          <%= link_to "Show", book_path(@book.id) %> |
          <%= link_to "Back", "/books" %>
        </span>
  
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to (image_tag book.user.get_profile_image(80,80)), user_path(book.user_id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
          </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'list', { books: @books, user: @user} %>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= image_tag book.user.get_profile_image(80,80) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
          </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
              <td><%= link_to (image_tag @user.get_profile_image(100,100)), user_path(@user.id) %><br>
              <%= link_to @user.name, user_path(@user.id) %>
              </td>

              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
                <td><%= link_to "Destroy",book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
      </table>
    </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>welcome to 
      <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
        <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!
      </h1>
      <p>In<strong><i class="fa-solid fa-book"></i>Bookers,</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>
      
      <div class="d-grid gap-2 col-10 mx-auto">
        <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block" %><br>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5190e400d3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
               <li>
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-house"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-users"></i>Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: 'nav-link text-light' do %>
                   <i class="fa-solid fa-book-open"></i>Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-sign-out-alt"></i>Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-house"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-link"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>    
      <%= yield %>
    </main>
      
    <footer>
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-12 d-flex align-items-center justify-content-center">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br>
        <label for="inputImage">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction, maxlength: 50%><br>

          <% unless @user.guest_user? %>
          <div class="row">
          <%= link_to "",edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
          </div>
          <% end %>

      <% end %>
    </div>
   </div>
</div>

app/views/users/index.html.erb
<%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= image_tag user.get_profile_image(80,80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
          <% end %>
          </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= link_to (image_tag book.user.get_profile_image(80,80)), user_path(@user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
          </table>
    </div>
  </div>
</div>